### PR TITLE
Add pkg/dev for Venture J Series 3030

### PR DESCRIPTION
**Pull request by sixtyfive**

### CODE REVIEW

**Comment by ubruhin** [comment]
Hi,

generally it looks very well! :+1: However, I have some comments:

- Some polygons are on layer "Documentation" but should be on "Top Documentation"
- The copper rectangle on the anode pad might lead to DRC warnings (because it has no net assigned) and doesn't help much anyway since it has no stopmask. Could we simply remove it for now? Some day LibrePCB might support arbitrary shaped pads, which would solve this issue nicely.
- Actually the idea is (more or less) to create separate devices for each MPN, since this will lead to a much more useful BOM. I see following options for this PR:
  - Just rename the device to the MPN you actually need currently.
  - If you have lot of time :grin:, create separate devices for each MPN of this series.
  - Maybe we could an exception here and accept the actually too generic device name :see_no_evil: 

And just out of curiosity, did you already create a PCB with this footprint and verified if it fits properly?

**Comment by sixtyfive** [comment]
Before I take a detailed look:

> MPN

= "Manufacturer's Part Number"? In this case I was working with `JB3030 3‐V`, but the family only consists of that, plus `JK3030 3‐V` as well as `JK3030 6‐V`, with no differences in packaging or pin assignments whatsoever, so manual copies would be quite feasible.

> And just out of curiosity, did you already create a PCB with this footprint and verified if it fits properly?

Confirmed fitting [and confirmed working](https://i.imgur.com/dUwsWY6.mp4) ;-)

**Comment by ubruhin** [comment]
> = "Manufacturer's Part Number"?

Correct :)

> In this case I was working with JB3030 3‐V, but the family only consists of that, plus JK3030 3‐V as well as JK3030 6‐V, with no differences in packaging or pin assignments whatsoever, so manual copies would be quite feasible.

Yeah since these three variants even have different electrical specifications, I'd prefer to have separate devices for them.

> Confirmed fitting and confirmed working ;-)

Nice! :smiley:

**Comment by sixtyfive** [comment]
FTR: I rly wish there could be a quick-and-dirty interim solution in LibrePCB itself for the rectangle-on-pad thing. Something like electively disabling that specific DRC warning within 1mm of the confines of the part, or something. No need for any UI, just a simple attribute in the `.lp`, `polygon a-b-c-d-e (drc force-off)`. Whatever, basically, just _any_thing.

**Review by ubruhin — APPROVED** [review]
Thanks a lot! :smiley:

**Pull request merged**
